arenas:
  winter:
    lobbyworld: "world"
    cageworld: "bridge2"
    arenaworld: "bridge2"
    name: "nature"
    players: 2
    # the block name must be all caps e.g. "ACACIA_BOAT"
    displayblock: "GRASS_BLOCK"

    lobbyx: -120
    lobbyy: 64
    lobbyz: 75

    cagex: 0
    cagey: 96
    cagez: -1

    xone: 0
    yone: 72
    zone: -25

    xtwo: 0
    ytwo: 72
    ztwo: 25

    # corners
    c1x: -14
    c1y: 53
    c1z: -34

    c2x: 23
    c2y: 94
    c2z: 26
