arenas:
  # just put something random for this
  nature:
    # name of world for lobby
    lobbyworld: "lobby"
    # world name of the cage
    cageworld: "bridge2"
    # world name of the spawns
    arenaworld: "bridge2"
    # name as it will show up in menus etc
    name: "nature"
    # ignore this
    players: 2
    # ignore this
    displayblock: "GRASS_BLOCK"

    # lobby cords leave at this
    lobbyx: 0
    lobbyy: 66
    lobbyz: 0
    # cage cords
    cagex: 0
    cagey: 96
    cagez: -1

    # spawn one cords
    xone: 0
    yone: 77
    zone: 25

    # spawn two cords
    xtwo: 0
    ytwo: 77
    ztwo: -25

    # corners for the schematic, make sure that all values in corner 2 are larger than in corner 1 because of worldedit being finicky. for example c1x MUST be less than c2x and c1y MUST be less than c2y.
    c1x: -14
    c1y: 53
    c1z: -34

    c2x: 23
    c2y: 94
    c2z: 26

    goal1x: 0
    goal1y: 70
    goal1z: 25

    goal2x: 0
    goal2y: 70
    goal2z: -25