arenas:
  winter:
    lobbyworld: "lobby"
    cageworld: "bridge2"
    arenaworld: "bridge2"
    name: "winter theme"
    players: 2
    # the block name must be all caps e.g. "ACACIA_BOAT"
    displayblock: "GRASS_BLOCK"

    lobbyx: 1
    lobbyy: 1
    lobbyz: 1

    cagex: 2
    cagey: 1
    cagez: 3

    xone: 10
    yone: 10
    zone: 10

    xtwo: 20
    ytwo: 20
    ztwo: 20

    # corners
    c1x: 1
    c1y: 1
    c1z: 1

    c2x: 10
    c2y: 70
    c2z: 100
