arenas:
  winter:
    lobbyworld: "world"
    cageworld: "bridge2"
    arenaworld: "bridge2"
    name: "nature"
    players: 2
    # the block name must be all caps e.g. "ACACIA_BOAT"
    displayblock: "GRASS_BLOCK"

    lobbyx: -120
    lobbyy: 64
    lobbyz: 75

    cagex: 17
    cagey: 82
    cagez: -3

    xone: 0
    yone: 72
    zone: -25

    xtwo: 0
    ytwo: 72
    ztwo: 25

    # corners
    c1x: -15
    c1y: 48
    c1z: 34

    c2x: 13
    c2y: 85
    c2z: -32
