name: SimpleBridge
version: 0.1.1
main: io.github.atultw.simplebridge.Main
api-version: 1.8
depend: [ Multiverse-Core, WorldEdit ]
commands:
  duel:
    description: Select a map to duel
    usage: /<command>

  hub:
    description: go to hub
    usage: /<command>

  h:
    description: go to hub
    usage: /<command>